# Generated by Django 6.0.1 on 2026-06-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_authentication', '0004_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('premium', 'Premium')], default='user', max_length=20),
        ),
    ]
